  ---
title: "Coursera Getting and Cleaning Data Project"
author: "Darion Lawson"
output:
  html_document:
    toc: yes
---
### Introduction

This document provides a description about the scripts and data. It also contains instructions to run the project.

Environment: This script was developed and tested on:

* Windows 64-bit operating system
* RStudio Version 0.98.1062

Inventory: The project directory contains the following files:

* readme.md: this document.
* run_analysis.R: the primary execution file
* getvalues.R: user defined function that takes a data.frame and regular expression string, and returns column values that match the regular expression.
* cleanfeaturenames.R: takes a dataframe and parses the column names into valid values.
* CodeBook.md: explains the data.
* project01_tidy.txt: the Tidy dataset that is generated by this code. 

### To run these scripts

Assumptions: 

* all project files must be downloaded into the same directory. 
* the source data files will be downloaded and extracted in the same directory as the project files.

To run this example:

1. Open run_analysis.R
2. Locate the line with the value: #**TODO:
3. Change the argument in the setwd() function to the location of the run_analysis.R 
   and other project files. Each line in the run_analysis.R file must be executed equentially. 
   Each task is organized into sections and described as a separate step.
4. The tidy dataset will be written to the project working directory (defined by the 'setwd' function).

### List of code execution steps

#### Preparation

* STEP 1: Set up the environment dependencies.
* STEP 2: Download and unzip the source data files.

#### Set up the training data

* STEP 3: Get the training data from x_train.txt.
* STEP 4: Get the list of features from features.txt and trim whitespace.
* STEP 5: Convert featurename values to valid column names.
* STEP 6: Use the list of features to create column names for the training data.
* STEP 7: Get activity id labels for traindata from y_train.txt.
* STEP 8: Get the subject Ids from subject_train.txt.
* STEP 9: Use the activitytrain variable to add a new column for activityId.
* STEP 10: Use the subjecttrain variable to add a new column for subjectId.

#### Set up the test Data

* STEP 11: Get the test data.
* STEP 12: Use the list of features to create column names for the test data.
* STEP 13: Get activity id labels for test data from y_test.txt.
* STEP 14: Get the subject Ids from subject_test.txt.
* STEP 15: Use the activitytest data to add a new column for activityId.
* STEP 16: Use the subjecttest to add a new column for subjectId.

#### Merge the training data and the test data into one dataframe

* STEP 17: Merge the training and test data.

#### Aggregate the data based on Activity Id AND SubjectId

* STEP 18: Get the column names that contain the value: 'mean'.
* STEP 19: Use descriptive activity names to name the activities in the data set.
* STEP 20: Create a subset of the data using the variables for mean across all measurements. 
* STEP 21: Convert the datatype to double.
* STEP 22: Add activityId and subjectId columns.
* STEP 23: Calculate mean of each ActivityId and Subject Id combination.

#### Create a molten data set and correct clean up the data 

* STEP 24: Melt the data frame.
* STEP 25: Create and populate a new timeScaleType column as raw or fourier.
* STEP 26: Populate measurementType column  as x-axis, y-axis, z-axis, or magnitude.
* STEP 27: Populate sensor column as gyro or accelerometer.
* STEP 28: Populate sensor subtype column as body or gravity.
* STEP 29: Populate movement type column as normal or jerk.
* STEP 30: Populate valueType column as mean or std.dev.
* STEP 31: Reorder columns.
* STEP 32: Remove the variable column with the original variable name.

#### Create a Tidy data set 

* STEP 33: Cast meltedReadings to move mean and std.dev into separate columns.
* STEP 34: Export the 'tidy' data set to .txt file in the working directory.

The data and supporting information for this project is courtesy of:

[1] Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz. 
Human Activity Recognition on Smartphones using a Multiclass Hardware-Friendly Support Vector Machine. International Workshop of Ambient Assisted Living (IWAAL 2012). Vitoria-Gasteiz, Spain. Dec 2012
